services:
  traefik:
    image: traefik:v2.11.38
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.mqtts.address=:8883
      - --certificatesresolvers.cloudflare.acme.email=${ADMIN_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
      - "127.0.0.1:17000:8080"
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "sh -c ':> /dev/tcp/127.0.0.1/80'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  net:
    external: true
    name: ${TRAEFIK_NET}
